name: Test mirror trigger
on:
  push:
    tags:
      - 'v*'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # - name: SAY HELLO
      # run: echo "hello mirror! tag was ${GITHUB_REF_NAME}"
      # - name: LIST REPO
      # run: ls -la
      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.11.*'
          modules: 'qtmultimedia'
      - name: Build
        run: |
          chmod +x compile.sh
          ./compile.sh
      - name: Package
        run: |
          chmod +x package-bin.sh
          ./package-bin.sh "${GITHUB_REF_NAME#v}"
      - name: List Output
        run: ls -a *.tar.gz
